version: '3'
services:
  cassandra-node1:
    image: bitnami/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=password123
    volumes:
      - /opt/development/containers/cassandra:/bitnami
    networks:
      - service_net
    ports:
          - "9042:9042"

  cassandra-node2:
    image: bitnami/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=password123
    networks:
      - service_net
      
networks: 
   service_net: